# Generated by Django 3.0.3 on 2020-03-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0003_auto_20200221_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
