# Generated by Django 3.0.3 on 2020-03-05 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0003_auto_20200221_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('expiration_date'), descending=True),), 'verbose_name': ('payment_type',), 'verbose_name_plural': ('payment_types',)},
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bangazon.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon.ProductType'),
        ),
    ]
