# Generated by Django 3.0.3 on 2020-03-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0004_auto_20200304_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
