# Generated by Django 3.0.3 on 2020-03-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0004_auto_20200304_1328'),
        ('bangazon', '0004_product_inventory'),
    ]

    operations = [
    ]
