# Generated by Django 3.0.3 on 2020-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0005_merge_20200306_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
