# Generated by Django 3.0.3 on 2020-03-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0004_product_inventory'),
        ('bangazon', '0005_auto_20200305_1433'),
    ]

    operations = [
    ]
