# Generated by Django 3.0.3 on 2020-03-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0005_merge_20200306_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
