# Generated by Django 3.0.3 on 2020-03-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0006_merge_20200305_1509'),
        ('bangazon', '0007_remove_product_deleted'),
        ('bangazon', '0005_merge_20200309_0958'),
    ]

    operations = [
    ]
