# Generated by Django 3.0.3 on 2020-03-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0006_merge_20200305_1509'),
        ('bangazon', '0006_auto_20200306_1036'),
        ('bangazon', '0003_auto_20200305_1333'),
        ('bangazon', '0007_remove_product_deleted'),
    ]

    operations = [
    ]
