# Generated by Django 3.0.3 on 2020-03-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0008_merge_20200309_1020'),
        ('bangazon', '0008_merge_20200309_1540'),
    ]

    operations = [
    ]
