# Generated by Django 3.0.3 on 2020-03-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0008_merge_20200309_1540'),
        ('bangazon', '0005_merge_20200305_1554'),
    ]

    operations = [
    ]
