# Generated by Django 3.0.3 on 2020-03-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0009_auto_20200309_1050'),
        ('bangazon', '0009_merge_20200309_1107'),
    ]

    operations = [
    ]
