# Generated by Django 3.0.3 on 2020-03-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0009_merge_20200309_1113'),
        ('bangazon', '0010_merge_20200309_1151'),
    ]

    operations = [
    ]
